### ISSUE TITLE
Cannot find 'auth' in scope

### ISSUE THREAD

**Issue by radughitescu** [hadiidbouk/SimpleOAuth2#3]
Hi, i've copied the example usage code but i don't know where you got that "auth" object, i've attached a picture that shows the issue below:
![image](https://user-images.githubusercontent.com/20221798/115969546-14c9df00-a546-11eb-8ab6-1f92fae8009f.png)

**Comment by hadiidbouk** [comment]
Well you need to use the `Oauth2Manager` like [here](https://github.com/hadiidbouk/SimpleOAuth2/blob/cdc47994e3c9d9dfb237d4943b7834e00cca0097/Shared/ContentView.swift#L28)

**Comment by radughitescu** [comment]
Great, that fixed it, thank a lot!
